version: '3.8'

services:
  db:
    image: mysql:8
    container_name: mysql-student
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: studentdb
      MYSQL_USER: studentuser
      MYSQL_PASSWORD: studentpass
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -P 3306 -uroot -proot || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 6
      start_period: 10s

  app:
    image: dridi-khalil_student-management:latest
    container_name: spring-student
    ports:
      - "8081:8081"
    environment:
      # datasource (redondant avec application.properties mais OK)
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/studentdb
      SPRING_DATASOURCE_USERNAME: studentuser
      SPRING_DATASOURCE_PASSWORD: studentpass
      # forcer le port côté Spring (assure la cohérence)
      SERVER_PORT: "8081"
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure

volumes:
  mysql-data:
