services:
  db:
    image: mysql:8
    container_name: mysql-student
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: studentdb
      MYSQL_USER: studentuser
      MYSQL_PASSWORD: studentpass
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  app:
    image: dridi-khalil_student-management:latest
    container_name: spring-student
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/studentdb
      SPRING_DATASOURCE_USERNAME: studentuser
      SPRING_DATASOURCE_PASSWORD: studentpass
      SERVER_PORT: "8081"
    depends_on:
      - db
    restart: always

volumes:
  mysql-data:

